---
- name: Ping Target
  hosts: 18.117.11.183
  become: yes
  gather_facts: no
  #become_user: "{{ ansible_user }}"
  #vars:
  #  ansible_user: ubuntu
  tasks:
    - name: Ping the host
      ping:

    - name: Check Disk Space
      shell: df -h
      register: disk_space_output

    - name: Show Disk Space Output
      debug:
        var: disk_space_output.stdout_lines
    - name: Update Package
      apt:
        update_cache: yes
    - name: Install nginx
      apt:
        name: nginx
        state: present
      notify: Start nginx

  handlers:
    - name: Start nginx
      service:
        name: nginx
        state: started

    
